import Vue from 'vue'
import  yjp from './dialog/main'
import toast from './toast/index'
import { Pagination,Carousel,CarouselItem , Tabs, TabPane, Table, TableColumn, Button, Input, Form, FormItem, Upload, Dialog, Select, Option, Checkbox, Loading, CheckboxButton, CheckboxGroup,Dropdown,DropdownMenu, DropdownItem, DatePicker } from 'element-ui'
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Pagination)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Button)
Vue.use(Input)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Upload)
Vue.use(Dialog)
Vue.use(Select)
Vue.use(Option)
Vue.use(Checkbox)
Vue.use(Loading)
Vue.use(CheckboxButton)
Vue.use(CheckboxGroup)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(DatePicker)
Vue.use(yjp)
Vue.use(toast)
